name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install -g @pika/pack
    - run: npm install
    - run: pika-pack
      env:
        CI: true
